### ISSUE TITLE
Create Account button doesn't work in Firefox

### ISSUE THREAD

**Issue by bc-AlyssNoland** [bigcommerce-labs/slate#85]
Invalid html syntax around the create account button prevents it from being usable in some browsers, such as Firefox. 

[Further documentation](https://www.w3.org/TR/2011/WD-html5-20110525/content-models.html#interactive-content)

**Comment by bc-mkatz** [comment]
We know that a simple fix/hack (at least interim) is to just make this a link, like other links across the header. Lose the capsule button shape around it, which has some aliasing anyway. Maybe give the link a unique color, as an alternative way to make it more prominent than the other links?

**Comment by bookernath** [comment]
http://stackoverflow.com/questions/16280684/nesting-a-inside-button-doesnt-work-in-firefox

Need to put the button inside the <a>.
